<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-eShop.MessageProcessor-4a52d418-8c19-4a81-9b98-2b3fb2a94ea5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Azure.Storage.Queues" Version="9.3.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\eShop.ServiceDefaults\eShop.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
